version: "3.8"
services:
  db:
    container_name: ${APP_NAME}Db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  app:
    container_name: ${APP_NAME}App
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    networks:
      - backend
    command: /bin/sh -c "npx prisma migrate deploy && npx prisma generate && npm run build && npm run start"
    depends_on:
      - db

  cypress:
    container_name: ${APP_NAME}Cypress
    build:
      context: .
      dockerfile: Dockerfile.cypress
    networks:
      - backend
    environment:
      - CYPRESS_baseUrl=http://app:3000
    volumes:
      - ./e2e/cypress:/e2e/cypress
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  backend:
