version: "3.8"
services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - backend
    command: /bin/sh -c "npx prisma migrate deploy && npx prisma generate && npm run build && npm run start"
    depends_on:
      - db
      - s3

  s3:
    container_name: ${APP_NAME}-s3
    build:
      context: .
      dockerfile: Dockerfile.s3
    networks:
      - backend
    ports:
      - 9000:9000

  db:
    container_name: ${APP_NAME}-db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8080:80
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
