version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - backend
    command: /bin/sh -c "npx prisma migrate dev && npx prisma studio & npm run dev"
    depends_on:
      - db
      - s3

  s3:
    container_name: s3
    build:
      context: .
      dockerfile: Dockerfile.s3
    volumes:
      - ./s3:/s3/s3
    networks:
      - backend
    ports:
      - 9000:9000

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
