import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { ClientOnly } from "@/components/client-only"
import { CreateStoreModal } from "@/components/create-store-modal"
import { Providers } from "@/components/providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {props.children}
          <ClientOnly>
            <CreateStoreModal />
          </ClientOnly>
        </Providers>
      </body>
    </html>
  )
}
