name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/ecommerce-dashboard
            docker-compose -f docker-compose.prod.yml down
            git fetch origin main
            git reset --hard origin/main
            npm run docker:prod
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
  