name: Deploy to VPS

on:
  workflow_run:
    workflows: [Test E2E]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/ecommerce-dashboard
            git fetch origin main
            git reset --hard origin/main
            npm run docker:prod
            docker container prune -f
            docker image prune -f
            echo Containers updated successfully.
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
