name: Test E2E

on:
  push:
    branches: main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DB
        run: |
          docker run \
          --name postgres \
          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          -p 5432:5432 \
          -d postgres:15

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL}}
          envkey_APP_NAME: ${{ secrets.APP_NAME}}
          envkey_EMAIL_FROM: ${{ secrets.EMAIL_FROM}}
          envkey_EMAIL_SERVER: ${{ secrets.EMAIL_SERVER}}
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
          envkey_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
          envkey_HOST: ${{ secrets.HOST}}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL}}
          envkey_NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL}}
          envkey_NEXT_PUBLIC_S3_BUCKET_NAME: ${{ secrets.NEXT_PUBLIC_S3_BUCKET_NAME}}
          envkey_NEXT_PUBLIC_S3_HOST: ${{ secrets.NEXT_PUBLIC_S3_HOST}}
          envkey_S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME}}
          envkey_S3_CLIENT_KEY: ${{ secrets.S3_CLIENT_KEY}}
          envkey_S3_CLIENT_SECRET: ${{ secrets.S3_CLIENT_SECRET}}
          envkey_S3_REGION: ${{ secrets.S3_REGION}}
          fail_on_empty: true

      - name: Build and start app
        run: |
          npm ci \
          && npx prisma migrate deploy \
          && npx prisma generate \
          && npm run build

      - name: Start server in the background
        run: npm start &

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: e2e
          wait-on: "http://localhost:3000"
